<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        //c07/c07-01.html
        //예외처리
        //구문 오류와 예외
        //오류의 종류
        //프로그래밍 언어의 오류에는 크게 2가지 종류가 있습니다.
        //- 프로그램 실행 전에 발생하는 오류
        //- 프로그램 실행 중에 발생하는 오류
        //프로그램 실행전에 발생하는 오류를 구문 오류라고 부르며,
        //프로그램 실행 중에 발생하는 오류를 예외 또는 런타임 오류라고
        //구분하여 부릅니다.

        //구문 오류
        //구문 오류는 괄호의 짝을 맞추지 않았다든지, 문자열을 열었는데
        //닫지 않았다든지 할 때 발생하는 오류입니다.
        //이러한 구문 오류가 있으면 웹 브라우저가 코드를 분석조차 하지 
        //못하므로 실행 되지 않습니다.

        //예외
        //예외 또는 런타임 오류는 실행 중에 발생하는 오류를 의미합니다.
        //실행 중에 발생하는 오류가 예외입니다.

        //기본 예외 처리
        //조건문을 사용해서 예외가 발생하지 않게 만드는 것을
        //기본 예외 처리라고 부릅니다.
        const h1=document.querySelector("h1")
        if(h1){
            h1.textContent="Hello"
        }else{
            console.log("h1 태그를 추출할 수 없습니다.")
        }

        //고급 예외 처리
        //try catch finally구문을 사용해서 예외를 처리하는 방법을
        //고급 예외 처리라고 부릅니다.
        try{
            //예외가 발생할 가능성이 있는 코드
        }catch(exception){
            //예외가 발생했을 때 실행할 코드
        }finally{
            //무조건 실행할 코드
            //finally 블록은 생략 가능하다
        }
        try{
            willExcept.byeBye()
            //위에서 예외가 발생하므로, 실행되지 않고 catch구문으로 이동
            console.log("try 구문의 마지막 줄")
        }catch(e){
            console.log("catch구문의 마지막줄")
        }

        //finally구문
        try{
            // willExcept.byeBye()
            //위에서 예외가 발생하므로, 실행되지 않고 catch구문으로 이동
            console.log("try 구문의 마지막 줄")
        }catch(e){
            console.log("catch구문의 마지막줄")
        }finally{
            //예외의 발생 여부와 상관 없이 무조건 실행됩니다.
            console.log("finally 구문의 마지막 줄")
        }
    </script>
</body>
</html>